### ISSUE TITLE
Zeichensatz für Eingabe bei Textfeld anzeigen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#103]
Wenn der User über das Eingabefeld hovert, soll ein Hinweis kommen/erscheinen, der auf den UTF-8-Zeichensatz hinweist.

**Comment by BenVonRuehrei** [comment]
Die UTF-8 Info würde ich eher in den Nutzer-Dokumentation mit aufnehmen.
Da ich die Hover Funktion bei manchen Eingabefeldern andres verwenden möchte

**Comment by a71na** [comment]
Das möchten wir lieber in die Benutzerdokum mitaufnehmen

**Comment by BenVonRuehrei** [comment]
Die User Doku wurde angefangen und der Punkt ist aufgenommen
