### ISSUE TITLE
Begrenzung der Länge von Texteingaben

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#11]
Um die Datenbank des Online-Umfragesystems vor zu langen Eingaben zu schützen, soll das System die Anzahl der einzugebenden Buchstaben auf 2048 begrenzen und bei Überschreitung eine Warnung/Fehlermeldung in roter Schrift unter dem entsprechenden Textfeld ausgeben.

**Comment by BenVonRuehrei** [comment]
EIn Zeichenlimit kann mit CSS im HTML-Body für alle Seiten festgelegt werden.

**Comment by a71na** [comment]
Das hat Timon bereits gepusht :).
