### ISSUE TITLE
Auswertbaren Fragenbogen gemeinsam mit Team 2 entwickeln

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#114]
Wir sollten uns zum Testen und Auswerten einen gemeinsamen Fragebogen aus verschiedenen Fragen zusammenstellen, der sich gut auswerten lässt. Diesen legen wir dann in einem SQL-Skript an und beide Gruppen verwenden den zum Testen.

**Comment by 12Jacky** [comment]
Wollen wir den Fragebogen dann vor der Grafik Anbindung auf eurer Homepage machen, so das wir gleich bei der Anbindung mit Kontrollieren ob alles Funktioniert. Oder haltet ihr das an der Stelle für zu früh und wollt das wann anders machen

**Comment by a71na** [comment]
Ich würde Euren Fragebogen dann nehmen und in die Datenbank "laden", damit wir den gleich zum Testen usw. drinnen haben. Schön wäre es, wenn ich den als entsprechenden SQL-Code bekommen würde. Wenn das nicht möglich ist, dann mache ich es selbst.

**Comment by a71na** [comment]
Haben wir soeben in SQL von Team 2 erhalten und in der Console unserer Datenbank ausgeführt. Jetzt fehlen nur noch sinnvolle Antworten, dann ist der Test-Datensatz fertig.

**Comment by a71na** [comment]
Der Fragebogen wurde hier hinzugefügt und getestet :-)
