### ISSUE TITLE
IDEE: Zurück-Button in der Fragebogen-Ansicht implementieren

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#119]
Wenn der User den Fragebogen ausfüllt, soll es die Möglichkeit geben über das Klicken eines Zurück-Buttons die bereits ausgefüllten Fragen noch einmal anzuschauen.

Dafür müssen wir die Antworten sowie auch die Position des Users im Fragebogen speichern, damit wir die vorherige Frage laden können.

**Comment by BenVonRuehrei** [comment]
Ist das wirklich wichtig/notwendig?

**Comment by a71na** [comment]
Nein, du hast recht. Durch den Zurück-Button im Browser und meiner hinzugefügten Funktionalität, dass bereits existierende Antworten von einem User überschrieben werden, ist dieses Issue nicht notwendig.
