### ISSUE TITLE
Entscheidung über die Datenbank

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#12]
Es muss sich für eine Datenbank (in Abhängigkeit von der Programmiersprache) entschieden werden. Unter Python macht sich SQLite sehr gut. Unter Java Spring Boot macht sich die H2-Datenbank besser.

Allgemein tendieren wir zu einer eingebetteten Datenbank. Diese hat zum Vorteil, dass kein zusätzlicher Server für die Datenbank instanziiert werden muss.

**Comment by d00mfry** [comment]
Ressource: https://www.sqlitetutorial.net/download-install-sqlite/

**Comment by BenVonRuehrei** [comment]
Aktuelle steht MS SQL zur Option
Die Datenbanktabellken werden voarb von @BenVonRuehrei in Excel als beispiel erstellt

**Comment by a71na** [comment]
Ich denke, wir verwenden vorerst die H2-Datenbank zum Programmieren und Testen verwenden. Vorerst ist sie noch memory-basiert. Später machen wir es file-basiert.

PostgreSQL halten wir uns auch noch offen.
