### ISSUE TITLE
Overflow Fehler durch default-Datentyp mit 255 Zeichen - das 256. Zeichen erzeugt einen Fehler. 

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#129]
Wenn im Textfeld der Umfrage ein Text mit 256 Zeichen eingegeben wird, wird eine Fehlermeldung ausgegeben. Es sollte allerdings möglich sein, das Maximum von 256 Zeichen ohne Probleme einzufügen. 

Grund hierfür ist der default-Datentyp, der von 0 - 255 geht, wir gingen von 1 - 256 aus. Daher überschreitet das 256. Zeichen das Limit.

**Comment by a71na** [comment]
Genau die H2-Datenbank hat als Datentyp Character Varying(255) angenommen.

**Comment by a71na** [comment]
Diesen Bug haben wir mit commit 0333911 behoben.
