### ISSUE TITLE
UTF-8-Symbol „ß“ im Fragentitel wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#130]
![kein scharfes S](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166112003/e29a1190-aff4-4bfe-a4eb-f4cc841f8d02)

Die Darstellung des "ß" wird nicht richtig angezeigt. Das Problem tritt in allen gängigen Internetbrowsern auf. 
Allerdings nur bei @d00mfry, bei den anderen scheint es zu funktionieren.

Könnte an der Entwicklungsumgebung liegen, womöglich low-prio freak accident, wenn wir am Schluss noch Zeit haben können wir das tacklen.

**Comment by a71na** [comment]
Das schauen wir uns nochmal an, ich bin gespannt, was Manjaro/Linux da macht :-)

**Comment by a71na** [comment]
Unter Linux hatte ich da ebenfalls keinerlei Probleme.

**Comment by BenVonRuehrei** [comment]
@d00mfry Bitte überprüfen ob das Problem auch auf deinem Arbeitslaptop vorliegt, wenn nein, dann könnnen wir den Issue schließen. Es funktioniert dann bei 4 von 5 Geräten

**Comment by BenVonRuehrei** [comment]
"Fehler" tritt zu selten auf bei 4 anderen nicht. Vermutlich falsche Einstellung in IDE.
Wird nicht weiter verfolgt
