### ISSUE TITLE
Leerzeichen bei Frageerstellung?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#132]
Akzeptieren wir Leerzeichen bei Frageerstellung? Bei der Probandenansicht sortieren wir Leerzeichen aber aus. Es könnten Edge Cases resultieren, z.B. in Frage "gefangen" sein.

**Comment by BenVonRuehrei** [comment]
Ich werde versuchen eine Mindesteingabe von einen Zeichen/Zahl in HTML zu erzwingen

**Comment by a71na** [comment]
Das hat Timon erledigt.

**Comment by a71na** [comment]
Hab den Fehler gefunden und zum Glück noch einen anderen Bug entdeckt => #147
