### ISSUE TITLE
Erneute Formularübermittlung?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#134]
Müsste es eine Bestätigung für erneute Formularübermittlung geben? Falls der Zurück-Button im Browser geklickt wird

**Comment by a71na** [comment]
Wir hatten die Diskussion zwar schon, aber damit wir es nochmal schriftlich haben, gebe ich mal ein Kommentar ab. Wir hatten überlegt, dass es im Rahmen der Fallstudie so ausreicht, wie es gerade ist. Also, dass sich da kein Bestätigungsfenster öffnet.
