### ISSUE TITLE
Position des Tooltips korrigieren

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#135]
Der Tooltip erscheint, wenn der User keine Auswahl getroffen hat und weiter gehen möchte.
Die Postition ist aktuell nicht optimal und muss korrigiert werden.

**Comment by a71na** [comment]
(╯°□°）╯︵ ┻━┻

**Comment by a71na** [comment]
Ich denke, auch das hat Timon erledigt.
