### ISSUE TITLE
Benutzerdokumentation anfangen

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#138]
Der Benutzer soll Zugriff auf eine Art Benutzerdokumentation haben. Mit dieser soll knapp, ausführlich und verständlich beschrieben sein, wie unser Umfragetool funktioniert.

.md-Datei wird bevorzugt, als .pdf ist aber ebenso erlaubt.

Inhalt:
+ Art des Benutzers für unser System
+ Was muss ich als Nutzer (des Frontends und als Admin) beachten
+ Einschränkungen des Systems, Software soll aber robust sein

**Comment by BenVonRuehrei** [comment]
Benutzer Doku ist in Arbeit und schon sehr umfangreich
