### ISSUE TITLE
Testing fortführen

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#149]
+ Testplan (nicht so ausführlich, konkret halten) und Testing nach der Zwischenvorlesung vom 11.06.2024

+ Nochmal prüfen, ob wir die Requirements/Issues auch testen können. Explorative Tests uvm.
+ Komponententests, um Schnittstellen zu testen

**Comment by a71na** [comment]
Dazu gehören auch Unit Tests und Exploratives Testen! Das haben wir heute besprochen und möchten wir angehen

**Comment by a71na** [comment]
Neuste Erkenntnis: SQL Injections wie DROP TABLE oder TRUNCATE TABLE könne uns durch JPA und Hibernate nichts anhaben. Die eingegebenen Queries werden einfach als Text/String in der Datenbank gespeichert.

**Comment by d00mfry** [comment]
J Unit Test für große Klassen angeschoben, Testing von groß nach klein.
Wird in der kommenden Woche fortgeführt.
