### ISSUE TITLE
Aufbau der Datenbank für das Online-Umfragesystem

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#15]
Die Datenbank soll Nutzer mit ihren Umfragen speichern. Dazu sollen die Fragen inkl. Fragetyp pro Umfrage sowie die dazugehörigen Antworten in Tabellen gespeichert werden.

Der User hat eine User-ID, einen Namen, eine E-Mail-Adresse und ein Passwort.
Die Umfrage speichert einmal die User-ID, die Umfrage-ID, die Formular-ID und den Titel der Umfrage.
Die Frage hat eine Frage-ID, die Frage als Text und einen Fragetyp.
Die Antwort speichert die Frage-ID, hat eine Antwort-ID und eine Antwort als Text.

Dies könnte wie folgt aussehen (ist aber natürlich noch nicht final):
![Datenbankschema Umfragesystem (1)](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/506b5347-6e62-42fd-b349-3c36820b2dc0)

**Comment by a71na** [comment]
Wir haben uns noch überlegt, dass man als Umfrage-Element auch Abschnitte hinzufügen kann. Dafür könnten wir einen weiteren Fragetyp anlegen und den Abschnitt als Frage "behandeln". 

Darüber hinaus könnten wir noch als Zukunftsthema festhalten, dass jedes Umfrage-Element eine laufende Nummer hat, damit man die Elemente auch in ihrer Position verschieben kann.

**Comment by d00mfry** [comment]
Aktuelles Problem: Darstellung verschiedener Ergebnisarten scheint zunächst sehr komplex.

Einfachste Ergebnisdarstellung wäre Stand jetzt der Radio-Button, weil hier nur verschiedene Zustände gespeichert werden müssten, @BenVonRuehrei und ich sind dran.

**Comment by d00mfry** [comment]
Aktuelle Idee für Ergebnisdarstellungsproblem: 

Einzelne Primärschlüssel aus jeweiligen Datenbanken werden zu einem Primärschlüssel zusammengefügt. Damit die einzelnen Schlüssel ablesbar bleiben, werden sie durch _ getrennt. 

Proband 1, der Frage 2 mit den Antworten 3, und 6 und 7 beantwortet würde also folgenden Ergebnisschlüssel erzeugen:

1_2_367;

Die Problematik des Textfeldes soll Stand jetzt wie folgt gelöst werden:

Es wird eine Logik eingebaut, welche prüft, ob es ein Textfeld als Antwortmöglichkeit gibt.

Wenn nein, so wird dem Ergebnisschlüssel (in diesem Fall 1_2_367) eine 0 angehängt, d.h. 1_2_367_0. 

Wenn ja, so wird dem Ergebnisschlüssel eine Zahl über 0 zugeordnet, geplant: einfach aufsteigend.

**Comment by d00mfry** [comment]
Nachtrag: Man könnte dann z.B. zwischen Umfragen, welche Antworten mit Textfeld und denen ohne Textfeld unterscheiden, im Hinblick auf die Analysefunktion.

Wir sollten allgemein darauf achten, dass die Daten so praktisch wie möglich an das Analyseteam geliefert werden. Nicht, dass das bis jetzt nicht passiert ist, aber ist vielleicht etwas, was man nicht ständig auf dem Schirm hat. Nur zum im Kopf behalten.

**Comment by BenVonRuehrei** [comment]
![Image](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166393049/d0d23ddf-d3a1-41f9-8549-52af19969d00)

**Comment by a71na** [comment]
Ich habe mir heute nochmal Gedanken gemacht, ich finde das Modell nicht schlecht und es ist auch nicht falsch, aber ich glaube, es geht einfacher. Jede Tabelle ist eine Entity-Klasse in Spring Boot.

Deshalb habe ich mir Folgendes überlegt:
Ich denke, wir können uns die Tabellen Ergebnis, die Auflösungstabelle und den Freitext sparen. Das, was die Auflösungstabelle macht, machen doch schon die einzelnen Schlüsselpaare, über die die Tabellen verknüpft sind. Wenn ich da an ein SELECT-Statement denke, dann schreibe ich eine WHERE-Bedingung und komme an alle Daten, die ich brauche.

Team 2 kann sich ebenfalls über ein SELECT-Statement über unsere Tabellen alle Daten holen, die sie brauchen. Selbstverständlich müssen wir uns da nochmal absprechen.

Wenn wir der Tabelle "Antwort" bereits für jeden Fragetyp Spalten mitgeben, dann können wir den Freitext auch in dieselbe Tabelle speichern. Die Fragen inkl. Antwortoptionen für den Umfragebogen setzen sich aus den gleichen Spalten in der Tabelle "Frage" zusammen, nur dass es dort für Radiobutton mehrere Spalten gibt, denn bei Radiobutton gibt es nur eine valide Antwort.

Was passiert mit den Spalten der anderen Fragetypen? Die bleiben einfach leer, wir füllen nur die Spalten des entsprechenden Fragetyps. Das sollte auch performant sein, weil Spalten/Tabellen, in denen nichts eingetragen wurde, werden einfach nicht beachtet. Die Tabelle "Antwort" würde also wie folgt aussehen:
![nr5tYWZJVqKqxr0I](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/3684b862-dd77-4ef3-bde9-e7d7b6a3b46f)

Antwort-ID würde ich zur User-ID abändern, da wir diese vermutlich gar nicht brauchen. Die Frage-ID reicht als Verknüpfung eigentlich aus.

Darüber hinaus würde ich die User-Tabelle, wenn ich so an das MVP denke, vorerst abändern zu einer Tabelle, in der wir die Probanden speichern. Grund dafür ist, dass es im MVP eh erst einmal nur einen "Admin"-User gibt, da es nur eine Ansicht gibt. Später, wenn es einen Login gäbe/gibt, brauchen wir sowieso zwei Tabellen für die User: einmal für die Forschenden und einmal für die Probanden.

Somit käme folgendes Schema heraus:
![Datenbankschema Umfragesystem](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/8e3354c0-0813-4377-94e9-f961feb9b306)

Mein Vorschlag: Ich persönlich würde erst einmal mit den vier Tabellen anfangen. Wenn wir beim Implementieren merken, dass die nicht ausreichen oder wir gewisse Daten nicht bekommen, kann man immer noch Tabellen hinzufügen. Wir können nicht alles ins kleinste Detail planen, lieber fangen wir einfach Mal an und probieren es aus :-).

Gerne können wir da die Tage nochmal drüber sprechen :). Vielleicht halte ich die verschiedenen Schemata in einer .md-Datei fest, dass wir da den Überblcik behalten.

**Comment by a71na** [comment]
Eine vorläufige Version ist in Spring Boot integriert/als entities implementiert
