### ISSUE TITLE
Integration mit Team-Analyse

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#154]
1. Team-Plattform erstellt Branch für Team-Analyse @a71na (erledigt am 14.06.2024 - Branch heißt R-integration)
2. Team-Plattform hilft bei Setup von Spring-Boot-Server, wenn notwendig @a71na (Support wurde am 17.06.2024 geleistet) 
3. Team-Analyse muss eine Schnittstelle zwischen Java und R erstellen, am besten in eigener Klasse @Abdullah-C58 
5. Team-Plattform stellt Datenbank online zur Verfügung (bereits erledigt von @a71na; siehe Wiki)
6. Team-Analyse muss eine HTML-Seite zur Anzeige der Analyse erstellen @12Jacky (Rückfragen an @BenVonRuehrei )

Zu erledigen bis 21.06.2024

**Comment by a71na** [comment]
Die Aufgaben unsererseits wurden erledigt. (Support und Beantworten von Fragen machen wir selbstverständlich weiterhin, sofern Fragen bestehen :))

**Comment by a71na** [comment]
Ich würde behaupten, dass die Integration abgeschlossen ist. Wir haben das in unserem Rahmen mögliche für die Integration getan :-)
