### ISSUE TITLE
Logout-Button auf dem Screen SurveyView hinzufügen

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#155]
Mit einem Klick auf den "Logout"-Button, welcher sich in dem SurveyView-Screen befindet, soll sich der Nutzer aus dem aktuellen Account ausloggen können.

Er soll nach dem Klicken des Buttons wieder auf der Login-Page landen.

**Comment by BenVonRuehrei** [comment]
Das Issue wollte ich grade erstellen

**Comment by BenVonRuehrei** [comment]
Logout-Button erstellt
