### ISSUE TITLE
Frontend - Screen für User Settings in HMTL bauen

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#158]
Wenn der Nutzer auf den Einstellungsbutton oben rechts im Header (auf dem SurveyView) klickt, dann soll sich eine Ansicht öffnen, in der er seine Benutzerdaten bearbeiten kann.

**Comment by BenVonRuehrei** [comment]
Seite wurde in HTML erstellt und gepusht
