### ISSUE TITLE
Wie werden Reqs innerhalb von Github strukturiert?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#16]
Sollte wirklich für jedes Req ein eigenes Issue aufgemacht werden? 

Problem: Wenig Struktur
-> Labels für die groben Bereiche vergeben
-> Grobe Bereiche als Issue aufsetzen und feinere Reqs in die Beschreibung (atomar?)
-> Ausreichend, Reqs aus Storyboard abzuleiten?

**Comment by d00mfry** [comment]
Erster Storyboard-Draft erzeugt bereits 5-7 Requirements pro Screen, bei bisher 8 Screens. Eindampfen?

**Comment by a71na** [comment]
Eine Idee von uns wären weitere Labels für größere Funktionen, die man diesen 5-7 Requirements mitgibt, aber das erscheint uns trotzdem unübersichtlich...

**Comment by BenVonRuehrei** [comment]
Der Storyboard-Draft gilt für die Forschenden-Verwaltungsansicht, hier wird die meiste Arbeit anfallen. Es muss dann noch an den RE sowie dem Storyboard für die Probanden-Ansicht ausgearbeitet werden

**Comment by drjs** [comment]
Sie haben schon recht, eine Anforderung hat atomar zu sein - also jedes Requirement ein Issue. Das sind ja für die screens nur knapp 60 Anforderungen, das ist so viel nicht. 
Die Lösung ist wahrscheinlich die GitHub-Projects-Funktion: https://github.com/features/issues
Einfach mal das Video gucken, das erklärt’s ganz gut. Nur keine Angst vor der Zahl der Issues!

**Comment by a71na** [comment]
Herzlichen Dank für die schnelle Antwort! Dann wissen wir Bescheid :-).
