### ISSUE TITLE
Textfeld "Username" erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#17]
editiert: Es muss eine Zeile für die Eingabe des Nutzernamens mit der Bezeichnung "Username" geben. Bei der Zeile muss es sich um ein Textfeld handeln. Der Nutzername muss zwischen 4 und 16 UTF-8-Zeichen enthalten.

**Comment by d00mfry** [comment]
Es muss eine Zeile für die Eingabe des Nutzernamens mit der Bezeichnung "Username" geben. Bei der Zeile muss es sich um ein Textfeld handeln. Der Nutzername muss zwischen 4 und 64 UTF-8-Zeichen enthalten.

Mit 18 px Abstand unter der Zeile für den Nutzernamen muss es eine zweite Zeile namens "Passwort" geben. Sie ist ebenfalls ein Textfeld. Das Passwort muss zwischen 8 und 64 UTF-8-Zeichen lang sein, mindestens einen Großbuchstaben, ein Sonderzeichen (! # $ % ( ) * + , - . / : ; = ? @ [ ] ^ _ { | } ~) und eine Ziffer von 0 bis 9 enthalten.

Darunter muss es mittig zu den beiden Zeilen einen "Login" Button mit den Abmessungen 10 px x 40 px geben. Er ermöglicht bei richtiger Eingabe der Logininformationen in die oben genannten beiden Zeilen den Login in das Umfrageportal.

**Comment by a71na** [comment]
Dieses Textfeld gibt es bereits und Funktionalität im Backend ist auch hinterlegt.
