### ISSUE TITLE
Fragen Ansicht Screen implementieren

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#18]
Es soll eine Übersicht über alle Fragen einer Umfrage geben.

Hierbei sollen die Fragen dynamisch aufgelistet sein. Jede Frage kann editiert oder gelöscht werden. 

Mit einem Klick auf den Löschen-Button soll die Frage innerhalb einer Umfrage aus der Datenbank gelöscht werden.
Mit einem Klick auf den Bearbeiten-Button kann eine Frage editiert werden.

**Comment by a71na** [comment]
Das dynamische Auflisten funktioniert schon, das Editieren geht noch nicht (Timon wollte HTML überarbeiten) und Delete geht auch noch nicht (da muss ich noch einmal schauen).

**Comment by a71na** [comment]
Erledigt :-)
