### ISSUE TITLE
Wie machen wir das fertige Projekt zugänglich?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#2]
Sollen wir eine Domain kaufen und eine Internetseite erstellen, um dort das Online-Umfragetool zugänglich zu machen?

Oder soll es eine App werden? Welche Art der Distribution?

**Comment by d00mfry** [comment]
Kompatibilität zwischen Umfragetool und Analysetool beachten

**Comment by a71na** [comment]
Ich denke, über die Domain können wir uns gegen Schluss hin noch Gedanken machen, wenn alles ordnungsgemäß läuft. Vorerst würde ich sagen, dass wir das Umfragesystem lokal entwickeln. Dafür können wir den localhost mit dem Port 8080 verwenden, um einen lokalen HTTP-Server zu erstellen, der auf Port 8080 "lauscht". Zur Definition: Port 8080 wird in der Regel für HTTP-Proxy-Server oder für Webserver verwendet.

**Comment by d00mfry** [comment]
Heißt das, dass wir die Publizierung des Ganzen sowieso über eine Domain machen? Weil wir ja theoretisch auch z.B. eine Java-App einfach über die Domain laufen lassen könnten. 

Dann wäre das Problem tatsächlich eins für später, wenn die fertige App sowieso in eine Internetseite integriert wird. Oder liege ich da falsch?

**Comment by a71na** [comment]
Die Frage verstehe ich nicht, aber ich denke, dass wir es nicht automatisch über eine Domain machen müssen. Das kostet uns ja nur Zeit und Geld. Meiner Meinung nach ist die Frage, wo und ob wir das ganze überhaupt öffentlich machen, zumindest am Anfang, wo wir aktuell stehen, noch nicht soo relevant.

Ein README mit Erläuterung, wie man das lokal zum Laufen bringt, würde dem Herrn Schlosser laut eigener Aussage ausreichen.

Den letzten Absatz verstehe ich nicht, ich frage dich da übermorgen im Meeting nochmal :).

**Comment by a71na** [comment]
Wir haben eine Entwickler- und Benutzerdokumentation. Mit der Entwicklerdoku kann jeder das Projekt clonen und bei sich einrichten
