### ISSUE TITLE
Frage Radiobutton 

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#20]
Es muss eine Ansicht geben, in der auf dem Standardbanner mit Standardabstand vom oberen Bildschirmrand ein Textfeld untergebracht ist. Der Inhalt lautet "Frage Name".

Darunter sind vertikal angeordnet die vom Nutzer festgelegte Anzahl der Radio Buttons.

Rechts von den Radiobuttons - mit Standardabstand - sind jeweils Textfelder mit dem Inhalt "Antwortoption"

**Comment by a71na** [comment]
Der Fragetyp ist soweit umgesetzt. Leon wird es noch ausgiebig testen :)
