### ISSUE TITLE
Mit React vertraut machen, in Spring Boot integrieren und HTML voranbringen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#29]
Verknüpfung mit SpringBoot

**Comment by a71na** [comment]
weiterer Technologietest mit Flutter low code

**Comment by a71na** [comment]
Flutterflow kann auch ein Backend zur Verfügung stellen und auch eine Verknüpfung zu SQLite herstellen. Also theoretisch könnte man alles in Flutterflow machen. Aber ich denke, dass eine klare Trennung von Front- und Backend besser wäre und wir dabei auch mehr lernen würden. Habe mir Flutterflow bereits angeschaut, Potenzial ist da. Ich habe die Erfahrung gemacht, dass man dafür lieber nicht Firefox, sondern Edge hernimmt. Firefox hat gelaggt und war kaum zu bedienen.

**Comment by a71na** [comment]
Inzwischen erscheint mir FlutterFlow nicht sooo geeignet. Evtl. teste ich bis Freitag einen Drag-and-Drop-Editor für HTML. Ansonsten möchte ich nochmal weiter recherchieren. Aktuell wäre ich noch an Angular mit Firebase interessiert. Mal sehen, was bis Donnerstag machbar ist.

**Comment by BenVonRuehrei** [comment]
Hab auch gelesen, dass Flutter überwiegen für die Mobile APP Entwicklung verwendet wird und nicht primiär für Web

**Comment by a71na** [comment]
https://teleporthq.io/professional-website-builder
=> Das ist ganz cool, das kann code in verschiedenen Sprachen generieren und man kann aus Figma exportieren

**Comment by BenVonRuehrei** [comment]
Siehr ganz geil aus. Können wir mal ausprobieren

**Comment by a71na** [comment]
React in Spring Boot integrieren, HTML mit verschiedenen Fragetypen ausprobieren
