### ISSUE TITLE
Wollen wir uns eigentlich einen Namen für das Tool überlegen?

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#31]
Fänd ich irgendwie mega, wenn das Umfrage-Tool auch einen Namen bekommt, so wie in unseren Businessideen auch :D. Falls ihr auch Lust habt, gerne Namensvorschläge als Comment :-)

**Comment by a71na** [comment]
Und brauchen wir ein Logo? (Über Flutterflow könnte man Logos recht einfach hinzufügen)

**Comment by d00mfry** [comment]
ChatGPT schlägt "Survey Master" vor :P

**Comment by a71na** [comment]
Ich habe irgendwie das Gefühl, dass das der Name bleiben wird :D
