### ISSUE TITLE
Wollen wir uns ein Farbschema überlegen?

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#32]
Wenn wir Flutterflow tatsächlich verwenden, wollen wir uns auf eine Farbrichtung einigen? Vielleicht habt ihr beim Erstellen der Screens schon in eurer Vorstellung Farben gesehen. Bin für wirklich alle Farben offen :).

**Comment by d00mfry** [comment]
Gerne, allerdings glaub ich dass es mit simplen Grauabstufungen getan ist. Ich denke mal man kann das relativ einfach umsetzen.

**Comment by a71na** [comment]
Edit: Es wurde zwar nicht FlutterFlow, aber durch die Verwendung von CSS haben wir uns für ein Farbschema entschieden :)

![WhatsApp Bild 2024-04-21 um 14 41 24_cdd6ef79](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/63ec6d34-f40f-4d52-a310-bccb67cb9d2e)

Farbpalette:
![WhatsApp Bild 2024-04-21 um 14 41 06_36a37792](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/054a3ab5-0186-445d-9942-c8f09090e8d7)


Alternativen waren:
![WhatsApp Bild 2024-04-20 um 17 57 57_d7232529](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/5a716f29-3f14-43c1-9b1a-cc1dc3593518)
