### ISSUE TITLE
Anlage von Issues im Projekt

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#34]
Estimate:

1 - niedriger Aufwand
2 - normaler Aufwand
3 - großer Aufwand

Priority:

P0 - hoch
P1 - mittel
P2 - niedirg

**Comment by a71na** [comment]
https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/wiki/Projects%E2%80%90Ansicht
