### ISSUE TITLE
MVC Modell Umfragetool erstellen und als .md-Datei bereitstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#37]

**Comment by a71na** [comment]
![Infrastruktur und MVC](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/eba96b91-6f1e-4587-96bd-2754dab36bcb)

Ablage der .md-Datei unter: main => Aufgaben => Infrastruktur und Architektur Übersicht.md
