### ISSUE TITLE
Wo wird jeweils programmiert?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#38]
Ich würde hier einmal gerne festhalten, welche Tools wir auf absehbare Zeit benutzen, und wie diese dann zusammenhängen. Mir fällt es etwas schwer, den Überblick zu behalten bei all den Sachen, die wir uns die letzte Zeit angeschaut haben.

**Comment by a71na** [comment]
- Java Spring Boot in IntelliJ
- HTML geht in IntelliJ mit Preview oder in WebStorm
- SQL brauchen wir gar nicht so, aber wenn, dann auf der Oberfläche, die die H2-Datenbank zur Verfügung stellt
