### ISSUE TITLE
Welche Programmiersprache wird verwendet?

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#4]
Ohne jetzt jemandem zu nahe treten zu wollen ist es doch wohl so, dass sich die Kenntnisse außerhalb von Java außer bei @a71na eher in Grenzen halten - Wollen wir das in Java umsetzen?

Was gibt es noch für Möglichkeiten?

Schlagworte:

Modulares Design (Umstellen des Fragebogens, unter Berücksichtigung sozialwissenschaftlicher Befunde)
Fragebogen besteht in erster Linie aus Text und/oder Auswahlmöglichkeiten

**Comment by a71na** [comment]
Nach dem heutigen Meeting stehen bisher Java Spring Boot und Python zur Auswahl (für das Backend). Frontend könnte HTML, CSS, Flutter oder Angular sein (?).

Die Datenbank könnte eine embedded Datenbank wie H2 oder SQLite3 sein.

**Comment by a71na** [comment]
Neue Ideen: Flutter ist nicht sonderlich geeignet für Webanwendungen. Vielleicht ist Angular mit Firebase eine Option. Und als Datenbank NoSQL, weil wir haben ja kein festes Datenbank-Schema. Letztendlich sieht jede Umfrage anders aus.

**Comment by BenVonRuehrei** [comment]
JS steht auch noch zur Option und das darauf basierende React, soll wohl für Web-Basiertebenutzeroberflächen gut sein

**Comment by d00mfry** [comment]
https://react.dev/

Hier das React-Intro - man könnte hier anknüpfen für das Analysetool

**Comment by BenVonRuehrei** [comment]
Aktuell stehen zur engeren Auswahl:

- React (JSX)
- Java(SpringBoot)
- HTML
- Datenbank SQL es wird ein Excel Beispiel erstellt
- Datenanalyse(Python)

**Comment by a71na** [comment]
![Infrastruktur - Übersicht über Komponenten](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/f49c26cc-b4e1-4522-8073-7c2c9622baab)
