### ISSUE TITLE
Button "Login" erstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#40]
Mit 18 px Abstand zentriert unter den beiden Zeilen "Username" und "Passwort" soll ein Button namens "Login" eingebaut werden. 

Nach dem Anklicken des Buttons sollen die Textfelder "Username" und "Passwort" auf Richtigkeit überprüft werden.

Ist die Richtigkeit gegeben, so ist das Einloggen erfolgreich und der Nutzer wird zum Screen "Umfragen Übersicht" weitergeleitet.

**Comment by a71na** [comment]
Der Login-Button ist erstellt und die Backend-Funktionalität ist bereits gestellt.
