### ISSUE TITLE
Button "Passwort vergessen?" erstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#41]
Mit 18 px Abstand unter dem "Login" Button soll es einen Button mit der Größe 36 * 128 px geben, welcher mit "Passwort vergessen?" betitelt wird. 

Klickt man ihn an, so wird man zu einem Formular weitergeleitet, welches eine neue Passwortvergabe ermöglicht.

**Comment by a71na** [comment]
Den Screen gibt es bisher nicht, den Link schon. Die Prio liegt aktuell bei den Hauptfunktionalitäten und beim Testing.

Da wir nicht mehr so viel Zeit haben, wird dieses Issue trotzdem einmal geschlossen und wieder geöffnet, wenn noch Zeit übrig ist.
