### ISSUE TITLE
Banner mit Inhalt aus "Username" erstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#42]
Das Element soll an oberster Stelle unterhalb der Adresszeile liegen.

Das Element soll 54 px hoch sein und die komplette Breite des Bildschirms bis hin zum Scrollbalken ausfüllen. 

Im Element soll der Username des angemeldeten Nutzerkontos stehen.

**Comment by BenVonRuehrei** [comment]
In CSS als ".header" classe erstellt. Inhalt muss dynamisch erzugt werden

**Comment by a71na** [comment]
Ich würde das gerne in einen zukünftigen Spint (nicht in Sprint 2) schieben, da diese Anforderung mit dem Login verknüpft ist und Login zählt nicht zum MVP.

**Comment by a71na** [comment]
Das habe ich beim Login jetzt doch mitgenmacht. Somit ist dies fertig.
