### ISSUE TITLE
Einstellungen-Button im Umfragenansicht-Screen erstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#43]
Am rechten Rand des Umfragenansicht-Screens, mit 18 px Abstand vom Scrollbalken, und den unteren und oberen Rändern, soll sich ein Zahnrad-Button von der Größe 12 * 12 px befinden.

Das Anklicken des Buttons leitet den angemeldeten Nutzer zu den Kontoeinstellungen weiter.

**Comment by BenVonRuehrei** [comment]
Einstellungsbutton sind soweit erzeugt. Müssen aber noch mit funktionen hinterlegt werden

**Comment by BenVonRuehrei** [comment]
Einstellungs Button ist erzeugt.

Folge Tätigkeiten:

#158 und #159
