### ISSUE TITLE
ER-Modell aus Issue #15 aktualisieren (nach dem Vorbild in Excel)

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#46]
Timons und Leons Excel-Datei nochmal als ER-Modell darstellen.

**Comment by BenVonRuehrei** [comment]
Am besten nicht im Darkmode ansehen oder in neuem Tap öffnen. Entity-Relationship-Modell

![Image](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166393049/d0d23ddf-d3a1-41f9-8549-52af19969d00)

**Comment by a71na** [comment]
Hier nochmal als Kopie:

Ich habe mir heute nochmal Gedanken gemacht, ich finde das Modell nicht schlecht und es ist auch nicht falsch, aber ich glaube, es geht einfacher. Jede Tabelle ist eine Entity-Klasse in Spring Boot.

Deshalb habe ich mir Folgendes überlegt:
Ich denke, wir können uns die Tabellen Ergebnis, die Auflösungstabelle und den Freitext sparen. Das, was die Auflösungstabelle macht, machen doch schon die einzelnen Schlüsselpaare, über die die Tabellen verknüpft sind. Wenn ich da an ein SELECT-Statement denke, dann schreibe ich eine WHERE-Bedingung und komme an alle Daten, die ich brauche.

Team 2 kann sich ebenfalls über ein SELECT-Statement über unsere Tabellen alle Daten holen, die sie brauchen. Selbstverständlich müssen wir uns da nochmal absprechen.

Wenn wir der Tabelle "Antwort" bereits für jeden Fragetyp Spalten mitgeben, dann können wir den Freitext auch in dieselbe Tabelle speichern. Die Fragen inkl. Antwortoptionen für den Umfragebogen setzen sich aus den gleichen Spalten in der Tabelle "Frage" zusammen, nur dass es dort für Radiobutton mehrere Spalten gibt, denn bei Radiobutton gibt es nur eine valide Antwort.

Was passiert mit den Spalten der anderen Fragetypen? Die bleiben einfach leer, wir füllen nur die Spalten des entsprechenden Fragetyps. Das sollte auch performant sein, weil Spalten/Tabellen, in denen nichts eingetragen wurde, werden einfach nicht beachtet. Die Tabelle "Antwort" würde also wie folgt aussehen:
![nr5tYWZJVqKqxr0I](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/3684b862-dd77-4ef3-bde9-e7d7b6a3b46f)

Antwort-ID würde ich zur User-ID abändern, da wir diese vermutlich gar nicht brauchen. Die Frage-ID reicht als Verknüpfung eigentlich aus.

Darüber hinaus würde ich die User-Tabelle, wenn ich so an das MVP denke, vorerst abändern zu einer Tabelle, in der wir die Probanden speichern. Grund dafür ist, dass es im MVP eh erst einmal nur einen "Admin"-User gibt, da es nur eine Ansicht gibt. Später, wenn es einen Login gäbe/gibt, brauchen wir sowieso zwei Tabellen für die User: einmal für die Forschenden und einmal für die Probanden. Oder wir verwalten die User weiterhin in einer Tabelle, aber einfach mit unterschiedlichen Rollen/Rechten.

Somit käme folgendes Schema heraus:
![Datenbankschema Umfragesystem](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166111939/8e3354c0-0813-4377-94e9-f961feb9b306)

Mein Vorschlag: Ich persönlich würde erst einmal mit den vier Tabellen anfangen. Wenn wir beim Implementieren merken, dass die nicht ausreichen oder wir gewisse Daten nicht bekommen, kann man immer noch Tabellen hinzufügen. Wir können nicht alles ins kleinste Detail planen, lieber fangen wir einfach Mal an und probieren es aus :-).

Gerne können wir da die Tage nochmal drüber sprechen :). Vielleicht halte ich die verschiedenen Schemata in einer .md-Datei fest, dass wir da den Überblick behalten.

**Comment by a71na** [comment]
Wir haben uns vorerst für mein Schema entschieden. Timons war nicht falsch, nur komplizierter 💚.

Für unser definiertes Minimum Viable Product (MVP) (siehe .md-Datei im Aufgaben-Ordner auf dem Main-Branch) ist die Datenbankstruktur vorerst hinreichend (siehe Überlegung im Kommentar oben darüber). Wir nehmen vorerst an, dass man das Datenbankschema in Zukunft reengieeren muss.
