### ISSUE TITLE
Banner mit Inhalt "Titel Umfrage" erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#47]
Wenn die Seite "Fragbogenansicht" geöffnet wird muss die Website im oberen Bereich einen Banner mit dem Titel der zuvor ausgewählten Umfrage anzeigen.

Das Element soll an oberster Stelle unterhalb der Adresszeile liegen.

Das Element soll 54 px hoch sein und die komplette Breite des Bildschirms bis hin zum Scrollbalken ausfüllen.

Banner #44

**Comment by a71na** [comment]
Erledigt :-)
