### ISSUE TITLE
Container mit Liste der Fragen erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#49]
Direkt unterhalb der #48 soll die Website einen Container anzeigen.
Der Kontainer soll alle zuvor erstellen Fragen der zuvor in der Umfrageansicht ausgewälten Umfrage, in einer Liste anzeigen.
Jede Frage soll in einer eigenen Spalte dargestellt werden
Die Fragen sollen aus der Datenbank "Frage" entnommen werden.

**Comment by a71na** [comment]
Das ist eine Altlast und schon längst fertig.
