### ISSUE TITLE
Onenote für alle zugänglich machen

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#5]
@a71na/ich muss noch mein Onenote-Notizbuch freigeben.

**Comment by a71na** [comment]
Liegt in unserem Team als Onenote-Package. Guckt mal, ob ihr das öffnen könnt :).

**Comment by d00mfry** [comment]
![One_Note_Fehler](https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/assets/166112003/862ed01c-45b6-4544-a227-20435f0e38c5)

Komme da leider nicht rein - OneNote einfach immer wieder gut ._.

**Comment by a71na** [comment]
Na super, habe nochmal einen Link mit Bearbeitungsrechten in unser Team in die Beiträge kopiert. Ich habe bisher keine Möglichkeit das Notizbuch als .one Datei in Teams reinzukopieren. OneDrive will nicht :c
