### ISSUE TITLE
Bearbeiten Button für Frage erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#50]
In der Frageliste #49 muss die Website einen Button 12px X 12px pro Frage enhalten, die es dem User ermöglicht die Frage zu bearbeiten.

Position: In der Splate der Frage vertikal zentriert mit Abstand von 80px zum rechten Rand

Funktion: Hypyerlink zu "Frage hinzufügen/bearbeiten" (jedoch mit den ausgefüllten Daten der gewählten Frage)

Der Button soll ein Stift-Icon in der mitte beinhalten.

**Comment by a71na** [comment]
Zwar ist es jetzt ein Zahnrad-Symbol geworden, aber dieses Feature wurde implementiert.
