### ISSUE TITLE
Löschen Button für Frage erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#51]
In der Frageliste #49  muss die Website einen Button 12px X 12px pro Frage enhalten, die es dem User ermöglicht die Frage zu löschen.

Position: In der Splate der Frage vertikal zentriert mit Abstand von 40px zum rechten Rand

Funktion: Hpyerlink zu "löschen umfrage/frage" 

Der Button soll ein Mülltonne-Icon in der mitte beinhalten.

**Comment by a71na** [comment]
Das funktioniert :-)
