### ISSUE TITLE
Umfrage hinzufügen Button erstellen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#54]
Das System muss einen "Umfrage hinzufügen" Button bereitstellen, um es Benutzern zu ermöglichen, neue Umfragen zu erstellen.

Benutzer m[ssen in der Lage sein, den "Umfrage hinzufügen" Button zu anzuklicken um per Mausklick eine neue Umfrage erstellen zu k;nnen.

**Comment by BenVonRuehrei** [comment]
Button ist erstellt. Funktion muss noch hinzugefügt werden

**Comment by a71na** [comment]
Aktueller Stand: Button ist klickbar und man kommt auf eine neue Seite "Umfrage-hinzufügen-Ansicht". Ich muss nur noch die Daten korrekt in der Datenbank speichern.

**Comment by a71na** [comment]
Neuer Stand: Die Informationen werden inzwischen in der DB gespeichert.

**Comment by a71na** [comment]
Das visuelle Hinzufügen ist erefolgt, somit ist diese Anforderung erledigt.
