### ISSUE TITLE
Seite Umfrage hinzufügen

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#65]
Es muss möglich sein, auf dieser Seite Umfragen anzulegen

Unter der Adresszeile soll das Standardbanner https://github.com/IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem/issues/44 als Header verwendet werden, in dem fester Text steht "Umfrage hinzufügen"

Es sollen zwei Standardbuttons implementiert werden, von denen einer "Speichern", der andere "Abbrechen" heisst.

**Comment by BenVonRuehrei** [comment]
Seite wurde in HTML erstellt

**Comment by a71na** [comment]
Darüber hinaus wurde auch die Funktionalität in Java implementiert.
