### ISSUE TITLE
Quellen in einer README.md hinzufügen für den HTML und CSS-Code

### ISSUE THREAD

**Issue by a71na** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#69]

**Comment by BenVonRuehrei** [comment]
https://www.w3schools.com/css/default.asp
https://www.w3schools.com/html/default.asp
https://stackoverflow.com/questions/42613359/how-does-flex-wrap-work-with-align-self-align-items-and-align-content
https://chat.openai.com/
https://www.perplexity.ai/

**Comment by a71na** [comment]
Hahbe sie noch in die entsprechenden README.md-Dateien eingefügt, danke <3
