### ISSUE TITLE
Story-Board erstellen

### ISSUE THREAD

**Issue by BenVonRuehrei** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#7]
Anhand des Story-Boards sollen die Konkreten Anforderungen abgeleitet werden.

**Comment by a71na** [comment]
Die Datei des Storyboards könntet ihr dann in den Ordner "Aufgaben" commiten (wenn ihr wollt :-) ).

**Comment by d00mfry** [comment]
Wie genau sollen die Reqs unterteilt werden? Jeder Bereich ein Issue und im Beschreibungstext genauere Reqs? Oder jede Req eigenes Issue?

**Comment by BenVonRuehrei** [comment]
Storyboard ist ausreichend in OneNote erstellt
