### ISSUE TITLE
Frage Check-Box

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#70]
Es muss eine Ansicht geben, in der auf dem Standardbanner mit Standardabstand vom oberen Bildschirmrand ein Textfeld untergebracht ist. Der Inhalt lautet "Frage Name". 

Darunter sind vertikal angeordnet die vom Nutzer festgelegte Anzahl der Checkboxen. 

Rechts von den Checkboxen - mit Standardabstand - sind jeweils Textfelder mit dem Inhalt "Antwortoption"

**Comment by a71na** [comment]
Das sollte inzwischen umgesetzt sein. Leon, unser Testmeister, wird das ausgiebig testen! :)
