### ISSUE TITLE
Frage Freitext

### ISSUE THREAD

**Issue by d00mfry** [IU-Internationale-Hochschule-Augsburg/fallstudie-thema-2-online-umfragesystem#71]
Es muss eine Ansicht geben, in der auf dem Standardbanner mit Standardabstand vom oberen Bildschirmrand ein Textfeld untergebracht ist. Der Inhalt lautet "Frage Name".

Darunter muss mit Standardabstand ein Textfeld implementiert werden, in welches eine Antwort eingetragen werden kann.

**Comment by a71na** [comment]
Funktioniert einwandfrei
